/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.AutomationCampaignSettingsProperty1;
import com.konfigthis.client.model.AutomationTrackingOptionsProperty;
import com.konfigthis.client.model.AutomationTriggerProperty1;
import com.konfigthis.client.model.CampaignReportSummaryProperty;
import com.konfigthis.client.model.ListProperty4;
import com.konfigthis.client.model.ResourceLink;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AutomationWorkflow1
 */
public class AutomationWorkflow1Test {
    private final AutomationWorkflow1 model = new AutomationWorkflow1();

    /**
     * Model tests for AutomationWorkflow1
     */
    @Test
    public void testAutomationWorkflow1() {
        // TODO: test AutomationWorkflow1
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'emailsSent'
     */
    @Test
    public void emailsSentTest() {
        // TODO: test emailsSent
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'settings'
     */
    @Test
    public void settingsTest() {
        // TODO: test settings
    }

    /**
     * Test the property 'tracking'
     */
    @Test
    public void trackingTest() {
        // TODO: test tracking
    }

    /**
     * Test the property 'triggerSettings'
     */
    @Test
    public void triggerSettingsTest() {
        // TODO: test triggerSettings
    }

    /**
     * Test the property 'reportSummary'
     */
    @Test
    public void reportSummaryTest() {
        // TODO: test reportSummary
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
