/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ResourceLink;
import com.konfigthis.client.model.VariateContentsPropertyInner3;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CampaignsSetContentResponse
 */
public class CampaignsSetContentResponseTest {
    private final CampaignsSetContentResponse model = new CampaignsSetContentResponse();

    /**
     * Model tests for CampaignsSetContentResponse
     */
    @Test
    public void testCampaignsSetContentResponse() {
        // TODO: test CampaignsSetContentResponse
    }

    /**
     * Test the property 'variateContents'
     */
    @Test
    public void variateContentsTest() {
        // TODO: test variateContents
    }

    /**
     * Test the property 'plainText'
     */
    @Test
    public void plainTextTest() {
        // TODO: test plainText
    }

    /**
     * Test the property 'html'
     */
    @Test
    public void htmlTest() {
        // TODO: test html
    }

    /**
     * Test the property 'archiveHtml'
     */
    @Test
    public void archiveHtmlTest() {
        // TODO: test archiveHtml
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
