/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ResourceLink;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConversationsGetMessageByIdResponse
 */
public class ConversationsGetMessageByIdResponseTest {
    private final ConversationsGetMessageByIdResponse model = new ConversationsGetMessageByIdResponse();

    /**
     * Model tests for ConversationsGetMessageByIdResponse
     */
    @Test
    public void testConversationsGetMessageByIdResponse() {
        // TODO: test ConversationsGetMessageByIdResponse
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'conversationId'
     */
    @Test
    public void conversationIdTest() {
        // TODO: test conversationId
    }

    /**
     * Test the property 'listId'
     */
    @Test
    public void listIdTest() {
        // TODO: test listId
    }

    /**
     * Test the property 'fromLabel'
     */
    @Test
    public void fromLabelTest() {
        // TODO: test fromLabel
    }

    /**
     * Test the property 'fromEmail'
     */
    @Test
    public void fromEmailTest() {
        // TODO: test fromEmail
    }

    /**
     * Test the property 'subject'
     */
    @Test
    public void subjectTest() {
        // TODO: test subject
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'read'
     */
    @Test
    public void readTest() {
        // TODO: test read
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
