/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ClicksProperty1Inner2;
import com.konfigthis.client.model.UniqueVisitsPropertyInner2;
import com.konfigthis.client.model.VisitsPropertyInner2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DailyClicksAndVisitsDataProperty1
 */
public class DailyClicksAndVisitsDataProperty1Test {
    private final DailyClicksAndVisitsDataProperty1 model = new DailyClicksAndVisitsDataProperty1();

    /**
     * Model tests for DailyClicksAndVisitsDataProperty1
     */
    @Test
    public void testDailyClicksAndVisitsDataProperty1() {
        // TODO: test DailyClicksAndVisitsDataProperty1
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    public void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'visits'
     */
    @Test
    public void visitsTest() {
        // TODO: test visits
    }

    /**
     * Test the property 'uniqueVisits'
     */
    @Test
    public void uniqueVisitsTest() {
        // TODO: test uniqueVisits
    }

}
