/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BillingAddressProperty1;
import com.konfigthis.client.model.ECommerceCustomerProperty3;
import com.konfigthis.client.model.ECommerceOrderLineItem1;
import com.konfigthis.client.model.OutreachProperty1;
import com.konfigthis.client.model.PromosPropertyInner;
import com.konfigthis.client.model.ShippingAddressProperty1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EcommerceUpdateSpecificOrderRequest
 */
public class EcommerceUpdateSpecificOrderRequestTest {
    private final EcommerceUpdateSpecificOrderRequest model = new EcommerceUpdateSpecificOrderRequest();

    /**
     * Model tests for EcommerceUpdateSpecificOrderRequest
     */
    @Test
    public void testEcommerceUpdateSpecificOrderRequest() {
        // TODO: test EcommerceUpdateSpecificOrderRequest
    }

    /**
     * Test the property 'customer'
     */
    @Test
    public void customerTest() {
        // TODO: test customer
    }

    /**
     * Test the property 'campaignId'
     */
    @Test
    public void campaignIdTest() {
        // TODO: test campaignId
    }

    /**
     * Test the property 'landingSite'
     */
    @Test
    public void landingSiteTest() {
        // TODO: test landingSite
    }

    /**
     * Test the property 'financialStatus'
     */
    @Test
    public void financialStatusTest() {
        // TODO: test financialStatus
    }

    /**
     * Test the property 'fulfillmentStatus'
     */
    @Test
    public void fulfillmentStatusTest() {
        // TODO: test fulfillmentStatus
    }

    /**
     * Test the property 'currencyCode'
     */
    @Test
    public void currencyCodeTest() {
        // TODO: test currencyCode
    }

    /**
     * Test the property 'orderTotal'
     */
    @Test
    public void orderTotalTest() {
        // TODO: test orderTotal
    }

    /**
     * Test the property 'orderUrl'
     */
    @Test
    public void orderUrlTest() {
        // TODO: test orderUrl
    }

    /**
     * Test the property 'discountTotal'
     */
    @Test
    public void discountTotalTest() {
        // TODO: test discountTotal
    }

    /**
     * Test the property 'taxTotal'
     */
    @Test
    public void taxTotalTest() {
        // TODO: test taxTotal
    }

    /**
     * Test the property 'shippingTotal'
     */
    @Test
    public void shippingTotalTest() {
        // TODO: test shippingTotal
    }

    /**
     * Test the property 'trackingCode'
     */
    @Test
    public void trackingCodeTest() {
        // TODO: test trackingCode
    }

    /**
     * Test the property 'processedAtForeign'
     */
    @Test
    public void processedAtForeignTest() {
        // TODO: test processedAtForeign
    }

    /**
     * Test the property 'cancelledAtForeign'
     */
    @Test
    public void cancelledAtForeignTest() {
        // TODO: test cancelledAtForeign
    }

    /**
     * Test the property 'updatedAtForeign'
     */
    @Test
    public void updatedAtForeignTest() {
        // TODO: test updatedAtForeign
    }

    /**
     * Test the property 'shippingAddress'
     */
    @Test
    public void shippingAddressTest() {
        // TODO: test shippingAddress
    }

    /**
     * Test the property 'billingAddress'
     */
    @Test
    public void billingAddressTest() {
        // TODO: test billingAddress
    }

    /**
     * Test the property 'promos'
     */
    @Test
    public void promosTest() {
        // TODO: test promos
    }

    /**
     * Test the property 'lines'
     */
    @Test
    public void linesTest() {
        // TODO: test lines
    }

    /**
     * Test the property 'outreach'
     */
    @Test
    public void outreachTest() {
        // TODO: test outreach
    }

    /**
     * Test the property 'trackingNumber'
     */
    @Test
    public void trackingNumberTest() {
        // TODO: test trackingNumber
    }

    /**
     * Test the property 'trackingCarrier'
     */
    @Test
    public void trackingCarrierTest() {
        // TODO: test trackingCarrier
    }

    /**
     * Test the property 'trackingUrl'
     */
    @Test
    public void trackingUrlTest() {
        // TODO: test trackingUrl
    }

}
