/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for EcommerceAddPromoRuleRequest
 */
public class EcommerceAddPromoRuleRequestTest {
    private final EcommerceAddPromoRuleRequest model = new EcommerceAddPromoRuleRequest();

    /**
     * Model tests for EcommerceAddPromoRuleRequest
     */
    @Test
    public void testEcommerceAddPromoRuleRequest() {
        // TODO: test EcommerceAddPromoRuleRequest
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'startsAt'
     */
    @Test
    public void startsAtTest() {
        // TODO: test startsAt
    }

    /**
     * Test the property 'endsAt'
     */
    @Test
    public void endsAtTest() {
        // TODO: test endsAt
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'createdAtForeign'
     */
    @Test
    public void createdAtForeignTest() {
        // TODO: test createdAtForeign
    }

    /**
     * Test the property 'updatedAtForeign'
     */
    @Test
    public void updatedAtForeignTest() {
        // TODO: test updatedAtForeign
    }

}
