/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests
 */
public class FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterestsTest {
    private final FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests model = new FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests();

    /**
     * Model tests for FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests
     */
    @Test
    public void testFacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests() {
        // TODO: test FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
