/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsInterests;
import com.konfigthis.client.model.FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsLocations;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs
 */
public class FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecsTest {
    private final FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs model = new FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs();

    /**
     * Model tests for FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs
     */
    @Test
    public void testFacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs() {
        // TODO: test FacebookAdsGetInfoResponseAllOf2AudienceTargetingSpecs
    }

    /**
     * Test the property 'gender'
     */
    @Test
    public void genderTest() {
        // TODO: test gender
    }

    /**
     * Test the property 'minAge'
     */
    @Test
    public void minAgeTest() {
        // TODO: test minAge
    }

    /**
     * Test the property 'maxAge'
     */
    @Test
    public void maxAgeTest() {
        // TODO: test maxAge
    }

    /**
     * Test the property 'locations'
     */
    @Test
    public void locationsTest() {
        // TODO: test locations
    }

    /**
     * Test the property 'interests'
     */
    @Test
    public void interestsTest() {
        // TODO: test interests
    }

}
