/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ErrorsPropertyInner;
import com.konfigthis.client.model.ListMembers;
import com.konfigthis.client.model.ResourceLink;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ListsBatchSubscribeOrUnsubscribe200Response
 */
public class ListsBatchSubscribeOrUnsubscribe200ResponseTest {
    private final ListsBatchSubscribeOrUnsubscribe200Response model = new ListsBatchSubscribeOrUnsubscribe200Response();

    /**
     * Model tests for ListsBatchSubscribeOrUnsubscribe200Response
     */
    @Test
    public void testListsBatchSubscribeOrUnsubscribe200Response() {
        // TODO: test ListsBatchSubscribeOrUnsubscribe200Response
    }

    /**
     * Test the property 'newMembers'
     */
    @Test
    public void newMembersTest() {
        // TODO: test newMembers
    }

    /**
     * Test the property 'updatedMembers'
     */
    @Test
    public void updatedMembersTest() {
        // TODO: test updatedMembers
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'totalCreated'
     */
    @Test
    public void totalCreatedTest() {
        // TODO: test totalCreated
    }

    /**
     * Test the property 'totalUpdated'
     */
    @Test
    public void totalUpdatedTest() {
        // TODO: test totalUpdated
    }

    /**
     * Test the property 'errorCount'
     */
    @Test
    public void errorCountTest() {
        // TODO: test errorCount
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
