/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivityClicksInner;
import com.konfigthis.client.model.ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivityImpressionsInner;
import com.konfigthis.client.model.ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivityRevenueInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity
 */
public class ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivityTest {
    private final ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity model = new ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity();

    /**
     * Model tests for ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity
     */
    @Test
    public void testReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity() {
        // TODO: test ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity
    }

    /**
     * Test the property 'clicks'
     */
    @Test
    public void clicksTest() {
        // TODO: test clicks
    }

    /**
     * Test the property 'impressions'
     */
    @Test
    public void impressionsTest() {
        // TODO: test impressions
    }

    /**
     * Test the property 'revenue'
     */
    @Test
    public void revenueTest() {
        // TODO: test revenue
    }

}
