/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.FacebookAdsListAdsResponseFacebookAdsInnerAllOf2Audience;
import com.konfigthis.client.model.RecipientsProperty3;
import com.konfigthis.client.model.ReportingListFacebookAdsReports200ResponseFacebookAdsInnerAllOf1Budget;
import com.konfigthis.client.model.ReportingListFacebookAdsReports200ResponseFacebookAdsInnerAllOf1Channel;
import com.konfigthis.client.model.ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1AudienceActivity;
import com.konfigthis.client.model.ReportingListFacebookAdsReportsResponseFacebookAdsInnerAllOf1ReportSummary;
import com.konfigthis.client.model.ResourceLink;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ReportingListFacebookAdsReports200ResponseFacebookAdsInner
 */
public class ReportingListFacebookAdsReports200ResponseFacebookAdsInnerTest {
    private final ReportingListFacebookAdsReports200ResponseFacebookAdsInner model = new ReportingListFacebookAdsReports200ResponseFacebookAdsInner();

    /**
     * Model tests for ReportingListFacebookAdsReports200ResponseFacebookAdsInner
     */
    @Test
    public void testReportingListFacebookAdsReports200ResponseFacebookAdsInner() {
        // TODO: test ReportingListFacebookAdsReports200ResponseFacebookAdsInner
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'webId'
     */
    @Test
    public void webIdTest() {
        // TODO: test webId
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'showReport'
     */
    @Test
    public void showReportTest() {
        // TODO: test showReport
    }

    /**
     * Test the property 'createTime'
     */
    @Test
    public void createTimeTest() {
        // TODO: test createTime
    }

    /**
     * Test the property 'startTime'
     */
    @Test
    public void startTimeTest() {
        // TODO: test startTime
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'canceledAt'
     */
    @Test
    public void canceledAtTest() {
        // TODO: test canceledAt
    }

    /**
     * Test the property 'publishedTime'
     */
    @Test
    public void publishedTimeTest() {
        // TODO: test publishedTime
    }

    /**
     * Test the property 'hasSegment'
     */
    @Test
    public void hasSegmentTest() {
        // TODO: test hasSegment
    }

    /**
     * Test the property 'reportSummary'
     */
    @Test
    public void reportSummaryTest() {
        // TODO: test reportSummary
    }

    /**
     * Test the property 'recipients'
     */
    @Test
    public void recipientsTest() {
        // TODO: test recipients
    }

    /**
     * Test the property 'thumbnail'
     */
    @Test
    public void thumbnailTest() {
        // TODO: test thumbnail
    }

    /**
     * Test the property 'emailSourceName'
     */
    @Test
    public void emailSourceNameTest() {
        // TODO: test emailSourceName
    }

    /**
     * Test the property 'pausedAt'
     */
    @Test
    public void pausedAtTest() {
        // TODO: test pausedAt
    }

    /**
     * Test the property 'endTime'
     */
    @Test
    public void endTimeTest() {
        // TODO: test endTime
    }

    /**
     * Test the property 'needsAttention'
     */
    @Test
    public void needsAttentionTest() {
        // TODO: test needsAttention
    }

    /**
     * Test the property 'wasCanceledByFacebook'
     */
    @Test
    public void wasCanceledByFacebookTest() {
        // TODO: test wasCanceledByFacebook
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'audience'
     */
    @Test
    public void audienceTest() {
        // TODO: test audience
    }

    /**
     * Test the property 'budget'
     */
    @Test
    public void budgetTest() {
        // TODO: test budget
    }

    /**
     * Test the property 'audienceActivity'
     */
    @Test
    public void audienceActivityTest() {
        // TODO: test audienceActivity
    }

    /**
     * Test the property 'links'
     */
    @Test
    public void linksTest() {
        // TODO: test links
    }

}
