/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * For sent campaigns, a summary of opens and clicks.
 */
@ApiModel(description = "For sent campaigns, a summary of opens and clicks.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class CampaignReportSummaryProperty1 {
  public static final String SERIALIZED_NAME_OPENS = "opens";
  @SerializedName(SERIALIZED_NAME_OPENS)
  private Integer opens;

  public static final String SERIALIZED_NAME_UNIQUE_OPENS = "unique_opens";
  @SerializedName(SERIALIZED_NAME_UNIQUE_OPENS)
  private Integer uniqueOpens;

  public static final String SERIALIZED_NAME_OPEN_RATE = "open_rate";
  @SerializedName(SERIALIZED_NAME_OPEN_RATE)
  private Double openRate;

  public static final String SERIALIZED_NAME_CLICKS = "clicks";
  @SerializedName(SERIALIZED_NAME_CLICKS)
  private Integer clicks;

  public static final String SERIALIZED_NAME_SUBSCRIBER_CLICKS = "subscriber_clicks";
  @SerializedName(SERIALIZED_NAME_SUBSCRIBER_CLICKS)
  private Integer subscriberClicks;

  public static final String SERIALIZED_NAME_CLICK_RATE = "click_rate";
  @SerializedName(SERIALIZED_NAME_CLICK_RATE)
  private Double clickRate;

  public CampaignReportSummaryProperty1() {
  }

  
  public CampaignReportSummaryProperty1(
     Integer opens, 
     Integer uniqueOpens, 
     Double openRate, 
     Integer clicks, 
     Integer subscriberClicks, 
     Double clickRate
  ) {
    this();
    this.opens = opens;
    this.uniqueOpens = uniqueOpens;
    this.openRate = openRate;
    this.clicks = clicks;
    this.subscriberClicks = subscriberClicks;
    this.clickRate = clickRate;
  }

   /**
   * The total number of opens for a campaign.
   * @return opens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total number of opens for a campaign.")

  public Integer getOpens() {
    return opens;
  }




   /**
   * The number of unique opens.
   * @return uniqueOpens
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of unique opens.")

  public Integer getUniqueOpens() {
    return uniqueOpens;
  }




   /**
   * The number of unique opens divided by the total number of successful deliveries.
   * @return openRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of unique opens divided by the total number of successful deliveries.")

  public Double getOpenRate() {
    return openRate;
  }




   /**
   * The total number of clicks for an campaign.
   * @return clicks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total number of clicks for an campaign.")

  public Integer getClicks() {
    return clicks;
  }




   /**
   * The number of unique clicks.
   * @return subscriberClicks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of unique clicks.")

  public Integer getSubscriberClicks() {
    return subscriberClicks;
  }




   /**
   * The number of unique clicks divided by the total number of successful deliveries.
   * @return clickRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of unique clicks divided by the total number of successful deliveries.")

  public Double getClickRate() {
    return clickRate;
  }



  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the CampaignReportSummaryProperty1 instance itself
   */
  public CampaignReportSummaryProperty1 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CampaignReportSummaryProperty1 campaignReportSummaryProperty1 = (CampaignReportSummaryProperty1) o;
    return Objects.equals(this.opens, campaignReportSummaryProperty1.opens) &&
        Objects.equals(this.uniqueOpens, campaignReportSummaryProperty1.uniqueOpens) &&
        Objects.equals(this.openRate, campaignReportSummaryProperty1.openRate) &&
        Objects.equals(this.clicks, campaignReportSummaryProperty1.clicks) &&
        Objects.equals(this.subscriberClicks, campaignReportSummaryProperty1.subscriberClicks) &&
        Objects.equals(this.clickRate, campaignReportSummaryProperty1.clickRate)&&
        Objects.equals(this.additionalProperties, campaignReportSummaryProperty1.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(opens, uniqueOpens, openRate, clicks, subscriberClicks, clickRate, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CampaignReportSummaryProperty1 {\n");
    sb.append("    opens: ").append(toIndentedString(opens)).append("\n");
    sb.append("    uniqueOpens: ").append(toIndentedString(uniqueOpens)).append("\n");
    sb.append("    openRate: ").append(toIndentedString(openRate)).append("\n");
    sb.append("    clicks: ").append(toIndentedString(clicks)).append("\n");
    sb.append("    subscriberClicks: ").append(toIndentedString(subscriberClicks)).append("\n");
    sb.append("    clickRate: ").append(toIndentedString(clickRate)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("opens");
    openapiFields.add("unique_opens");
    openapiFields.add("open_rate");
    openapiFields.add("clicks");
    openapiFields.add("subscriber_clicks");
    openapiFields.add("click_rate");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to CampaignReportSummaryProperty1
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!CampaignReportSummaryProperty1.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in CampaignReportSummaryProperty1 is not found in the empty JSON string", CampaignReportSummaryProperty1.openapiRequiredFields.toString()));
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!CampaignReportSummaryProperty1.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'CampaignReportSummaryProperty1' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<CampaignReportSummaryProperty1> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(CampaignReportSummaryProperty1.class));

       return (TypeAdapter<T>) new TypeAdapter<CampaignReportSummaryProperty1>() {
           @Override
           public void write(JsonWriter out, CampaignReportSummaryProperty1 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public CampaignReportSummaryProperty1 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             CampaignReportSummaryProperty1 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of CampaignReportSummaryProperty1 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of CampaignReportSummaryProperty1
  * @throws IOException if the JSON string is invalid with respect to CampaignReportSummaryProperty1
  */
  public static CampaignReportSummaryProperty1 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, CampaignReportSummaryProperty1.class);
  }

 /**
  * Convert an instance of CampaignReportSummaryProperty1 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

