/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * FacebookAdsGetInfoResponseAllOf2AudienceEmailSource
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class FacebookAdsGetInfoResponseAllOf2AudienceEmailSource {
  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_IS_SEGMENT = "is_segment";
  @SerializedName(SERIALIZED_NAME_IS_SEGMENT)
  private Boolean isSegment;

  public static final String SERIALIZED_NAME_SEGMENT_TYPE = "segment_type";
  @SerializedName(SERIALIZED_NAME_SEGMENT_TYPE)
  private String segmentType;

  public static final String SERIALIZED_NAME_LIST_NAME = "list_name";
  @SerializedName(SERIALIZED_NAME_LIST_NAME)
  private String listName;

  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource() {
  }

  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource name(String name) {
    
    
    
    
    this.name = name;
    return this;
  }

   /**
   * Email source name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Email source name")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    
    
    
    this.name = name;
  }


  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource type(String type) {
    
    
    
    
    this.type = type;
    return this;
  }

   /**
   * Type of the email source
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Type of the email source")

  public String getType() {
    return type;
  }


  public void setType(String type) {
    
    
    
    this.type = type;
  }


  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource isSegment(Boolean isSegment) {
    
    
    
    
    this.isSegment = isSegment;
    return this;
  }

   /**
   * Is the source reference a segment
   * @return isSegment
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Is the source reference a segment")

  public Boolean getIsSegment() {
    return isSegment;
  }


  public void setIsSegment(Boolean isSegment) {
    
    
    
    this.isSegment = isSegment;
  }


  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource segmentType(String segmentType) {
    
    
    
    
    this.segmentType = segmentType;
    return this;
  }

   /**
   * Segment type if this source is tied to a segment
   * @return segmentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Segment type if this source is tied to a segment")

  public String getSegmentType() {
    return segmentType;
  }


  public void setSegmentType(String segmentType) {
    
    
    
    this.segmentType = segmentType;
  }


  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource listName(String listName) {
    
    
    
    
    this.listName = listName;
    return this;
  }

   /**
   * Associated list name to the source
   * @return listName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Associated list name to the source")

  public String getListName() {
    return listName;
  }


  public void setListName(String listName) {
    
    
    
    this.listName = listName;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the FacebookAdsGetInfoResponseAllOf2AudienceEmailSource instance itself
   */
  public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FacebookAdsGetInfoResponseAllOf2AudienceEmailSource facebookAdsGetInfoResponseAllOf2AudienceEmailSource = (FacebookAdsGetInfoResponseAllOf2AudienceEmailSource) o;
    return Objects.equals(this.name, facebookAdsGetInfoResponseAllOf2AudienceEmailSource.name) &&
        Objects.equals(this.type, facebookAdsGetInfoResponseAllOf2AudienceEmailSource.type) &&
        Objects.equals(this.isSegment, facebookAdsGetInfoResponseAllOf2AudienceEmailSource.isSegment) &&
        Objects.equals(this.segmentType, facebookAdsGetInfoResponseAllOf2AudienceEmailSource.segmentType) &&
        Objects.equals(this.listName, facebookAdsGetInfoResponseAllOf2AudienceEmailSource.listName)&&
        Objects.equals(this.additionalProperties, facebookAdsGetInfoResponseAllOf2AudienceEmailSource.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, type, isSegment, segmentType, listName, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FacebookAdsGetInfoResponseAllOf2AudienceEmailSource {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    isSegment: ").append(toIndentedString(isSegment)).append("\n");
    sb.append("    segmentType: ").append(toIndentedString(segmentType)).append("\n");
    sb.append("    listName: ").append(toIndentedString(listName)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("name");
    openapiFields.add("type");
    openapiFields.add("is_segment");
    openapiFields.add("segment_type");
    openapiFields.add("list_name");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to FacebookAdsGetInfoResponseAllOf2AudienceEmailSource
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!FacebookAdsGetInfoResponseAllOf2AudienceEmailSource.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in FacebookAdsGetInfoResponseAllOf2AudienceEmailSource is not found in the empty JSON string", FacebookAdsGetInfoResponseAllOf2AudienceEmailSource.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("name") != null && !jsonObj.get("name").isJsonNull()) && !jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
      if ((jsonObj.get("segment_type") != null && !jsonObj.get("segment_type").isJsonNull()) && !jsonObj.get("segment_type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `segment_type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("segment_type").toString()));
      }
      if ((jsonObj.get("list_name") != null && !jsonObj.get("list_name").isJsonNull()) && !jsonObj.get("list_name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `list_name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("list_name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!FacebookAdsGetInfoResponseAllOf2AudienceEmailSource.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'FacebookAdsGetInfoResponseAllOf2AudienceEmailSource' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<FacebookAdsGetInfoResponseAllOf2AudienceEmailSource> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(FacebookAdsGetInfoResponseAllOf2AudienceEmailSource.class));

       return (TypeAdapter<T>) new TypeAdapter<FacebookAdsGetInfoResponseAllOf2AudienceEmailSource>() {
           @Override
           public void write(JsonWriter out, FacebookAdsGetInfoResponseAllOf2AudienceEmailSource value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public FacebookAdsGetInfoResponseAllOf2AudienceEmailSource read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             FacebookAdsGetInfoResponseAllOf2AudienceEmailSource instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of FacebookAdsGetInfoResponseAllOf2AudienceEmailSource given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of FacebookAdsGetInfoResponseAllOf2AudienceEmailSource
  * @throws IOException if the JSON string is invalid with respect to FacebookAdsGetInfoResponseAllOf2AudienceEmailSource
  */
  public static FacebookAdsGetInfoResponseAllOf2AudienceEmailSource fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, FacebookAdsGetInfoResponseAllOf2AudienceEmailSource.class);
  }

 /**
  * Convert an instance of FacebookAdsGetInfoResponseAllOf2AudienceEmailSource to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

