/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * A single instance of a campaign referral.
 */
@ApiModel(description = "A single instance of a campaign referral.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class Referrer {
  public static final String SERIALIZED_NAME_REFERRER = "referrer";
  @SerializedName(SERIALIZED_NAME_REFERRER)
  private String referrer;

  public static final String SERIALIZED_NAME_CLICKS = "clicks";
  @SerializedName(SERIALIZED_NAME_CLICKS)
  private Integer clicks;

  public static final String SERIALIZED_NAME_FIRST_CLICK = "first_click";
  @SerializedName(SERIALIZED_NAME_FIRST_CLICK)
  private OffsetDateTime firstClick;

  public static final String SERIALIZED_NAME_LAST_CLICK = "last_click";
  @SerializedName(SERIALIZED_NAME_LAST_CLICK)
  private OffsetDateTime lastClick;

  public Referrer() {
  }

  public Referrer referrer(String referrer) {
    
    
    
    
    this.referrer = referrer;
    return this;
  }

   /**
   * A referrer (truncated to 100 bytes).
   * @return referrer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A referrer (truncated to 100 bytes).")

  public String getReferrer() {
    return referrer;
  }


  public void setReferrer(String referrer) {
    
    
    
    this.referrer = referrer;
  }


  public Referrer clicks(Integer clicks) {
    
    
    
    
    this.clicks = clicks;
    return this;
  }

   /**
   * The number of clicks a single referrer generated.
   * @return clicks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The number of clicks a single referrer generated.")

  public Integer getClicks() {
    return clicks;
  }


  public void setClicks(Integer clicks) {
    
    
    
    this.clicks = clicks;
  }


  public Referrer firstClick(OffsetDateTime firstClick) {
    
    
    
    
    this.firstClick = firstClick;
    return this;
  }

   /**
   * The timestamp for the first click from this referrer.
   * @return firstClick
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The timestamp for the first click from this referrer.")

  public OffsetDateTime getFirstClick() {
    return firstClick;
  }


  public void setFirstClick(OffsetDateTime firstClick) {
    
    
    
    this.firstClick = firstClick;
  }


  public Referrer lastClick(OffsetDateTime lastClick) {
    
    
    
    
    this.lastClick = lastClick;
    return this;
  }

   /**
   * The timestamp for the last click from this referrer.
   * @return lastClick
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The timestamp for the last click from this referrer.")

  public OffsetDateTime getLastClick() {
    return lastClick;
  }


  public void setLastClick(OffsetDateTime lastClick) {
    
    
    
    this.lastClick = lastClick;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the Referrer instance itself
   */
  public Referrer putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Referrer referrer = (Referrer) o;
    return Objects.equals(this.referrer, referrer.referrer) &&
        Objects.equals(this.clicks, referrer.clicks) &&
        Objects.equals(this.firstClick, referrer.firstClick) &&
        Objects.equals(this.lastClick, referrer.lastClick)&&
        Objects.equals(this.additionalProperties, referrer.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(referrer, clicks, firstClick, lastClick, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Referrer {\n");
    sb.append("    referrer: ").append(toIndentedString(referrer)).append("\n");
    sb.append("    clicks: ").append(toIndentedString(clicks)).append("\n");
    sb.append("    firstClick: ").append(toIndentedString(firstClick)).append("\n");
    sb.append("    lastClick: ").append(toIndentedString(lastClick)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("referrer");
    openapiFields.add("clicks");
    openapiFields.add("first_click");
    openapiFields.add("last_click");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to Referrer
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!Referrer.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Referrer is not found in the empty JSON string", Referrer.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("referrer") != null && !jsonObj.get("referrer").isJsonNull()) && !jsonObj.get("referrer").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `referrer` to be a primitive type in the JSON string but got `%s`", jsonObj.get("referrer").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Referrer.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Referrer' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Referrer> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Referrer.class));

       return (TypeAdapter<T>) new TypeAdapter<Referrer>() {
           @Override
           public void write(JsonWriter out, Referrer value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public Referrer read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             Referrer instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Referrer given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Referrer
  * @throws IOException if the JSON string is invalid with respect to Referrer
  */
  public static Referrer fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Referrer.class);
  }

 /**
  * Convert an instance of Referrer to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

