/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.SendingScheduleProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * [RSS](https://mailchimp.com/help/share-your-blog-posts-with-mailchimp/) options, specific to an RSS campaign.
 */
@ApiModel(description = "[RSS](https://mailchimp.com/help/share-your-blog-posts-with-mailchimp/) options, specific to an RSS campaign.")@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class RSSOptionsProperty {
  public static final String SERIALIZED_NAME_FEED_URL = "feed_url";
  @SerializedName(SERIALIZED_NAME_FEED_URL)
  private URI feedUrl;

  /**
   * The frequency of the RSS Campaign.
   */
  @JsonAdapter(FrequencyEnum.Adapter.class)
 public enum FrequencyEnum {
    DAILY("daily"),
    
    WEEKLY("weekly"),
    
    MONTHLY("monthly");

    private String value;

    FrequencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static FrequencyEnum fromValue(String value) {
      for (FrequencyEnum b : FrequencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<FrequencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final FrequencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public FrequencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return FrequencyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_FREQUENCY = "frequency";
  @SerializedName(SERIALIZED_NAME_FREQUENCY)
  private FrequencyEnum frequency;

  public static final String SERIALIZED_NAME_SCHEDULE = "schedule";
  @SerializedName(SERIALIZED_NAME_SCHEDULE)
  private SendingScheduleProperty schedule;

  public static final String SERIALIZED_NAME_CONSTRAIN_RSS_IMG = "constrain_rss_img";
  @SerializedName(SERIALIZED_NAME_CONSTRAIN_RSS_IMG)
  private Boolean constrainRssImg;

  public RSSOptionsProperty() {
  }

  public RSSOptionsProperty feedUrl(URI feedUrl) {
    
    
    
    
    this.feedUrl = feedUrl;
    return this;
  }

   /**
   * The URL for the RSS feed.
   * @return feedUrl
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The URL for the RSS feed.")

  public URI getFeedUrl() {
    return feedUrl;
  }


  public void setFeedUrl(URI feedUrl) {
    
    
    
    this.feedUrl = feedUrl;
  }


  public RSSOptionsProperty frequency(FrequencyEnum frequency) {
    
    
    
    
    this.frequency = frequency;
    return this;
  }

   /**
   * The frequency of the RSS Campaign.
   * @return frequency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The frequency of the RSS Campaign.")

  public FrequencyEnum getFrequency() {
    return frequency;
  }


  public void setFrequency(FrequencyEnum frequency) {
    
    
    
    this.frequency = frequency;
  }


  public RSSOptionsProperty schedule(SendingScheduleProperty schedule) {
    
    
    
    
    this.schedule = schedule;
    return this;
  }

   /**
   * Get schedule
   * @return schedule
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public SendingScheduleProperty getSchedule() {
    return schedule;
  }


  public void setSchedule(SendingScheduleProperty schedule) {
    
    
    
    this.schedule = schedule;
  }


  public RSSOptionsProperty constrainRssImg(Boolean constrainRssImg) {
    
    
    
    
    this.constrainRssImg = constrainRssImg;
    return this;
  }

   /**
   * Whether to add CSS to images in the RSS feed to constrain their width in campaigns.
   * @return constrainRssImg
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Whether to add CSS to images in the RSS feed to constrain their width in campaigns.")

  public Boolean getConstrainRssImg() {
    return constrainRssImg;
  }


  public void setConstrainRssImg(Boolean constrainRssImg) {
    
    
    
    this.constrainRssImg = constrainRssImg;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the RSSOptionsProperty instance itself
   */
  public RSSOptionsProperty putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RSSOptionsProperty rsSOptionsProperty = (RSSOptionsProperty) o;
    return Objects.equals(this.feedUrl, rsSOptionsProperty.feedUrl) &&
        Objects.equals(this.frequency, rsSOptionsProperty.frequency) &&
        Objects.equals(this.schedule, rsSOptionsProperty.schedule) &&
        Objects.equals(this.constrainRssImg, rsSOptionsProperty.constrainRssImg)&&
        Objects.equals(this.additionalProperties, rsSOptionsProperty.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(feedUrl, frequency, schedule, constrainRssImg, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RSSOptionsProperty {\n");
    sb.append("    feedUrl: ").append(toIndentedString(feedUrl)).append("\n");
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    schedule: ").append(toIndentedString(schedule)).append("\n");
    sb.append("    constrainRssImg: ").append(toIndentedString(constrainRssImg)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("feed_url");
    openapiFields.add("frequency");
    openapiFields.add("schedule");
    openapiFields.add("constrain_rss_img");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("feed_url");
    openapiRequiredFields.add("frequency");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to RSSOptionsProperty
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!RSSOptionsProperty.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in RSSOptionsProperty is not found in the empty JSON string", RSSOptionsProperty.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : RSSOptionsProperty.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("feed_url").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `feed_url` to be a primitive type in the JSON string but got `%s`", jsonObj.get("feed_url").toString()));
      }
      if (!jsonObj.get("frequency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `frequency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("frequency").toString()));
      }
      // validate the optional field `schedule`
      if (jsonObj.get("schedule") != null && !jsonObj.get("schedule").isJsonNull()) {
        SendingScheduleProperty.validateJsonObject(jsonObj.getAsJsonObject("schedule"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!RSSOptionsProperty.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'RSSOptionsProperty' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<RSSOptionsProperty> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(RSSOptionsProperty.class));

       return (TypeAdapter<T>) new TypeAdapter<RSSOptionsProperty>() {
           @Override
           public void write(JsonWriter out, RSSOptionsProperty value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public RSSOptionsProperty read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             RSSOptionsProperty instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of RSSOptionsProperty given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of RSSOptionsProperty
  * @throws IOException if the JSON string is invalid with respect to RSSOptionsProperty
  */
  public static RSSOptionsProperty fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, RSSOptionsProperty.class);
  }

 /**
  * Convert an instance of RSSOptionsProperty to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

