/*
 * Mailchimp Marketing API
 * Mailchimp is a marketing platform for small businesses. It offers an all-in-one marketing solution that includes email marketing, ads, landing pages, and automation. With Mailchimp, businesses can design and send targeted campaigns, analyze their performance, and grow their audience.
 *
 * The version of the OpenAPI document: 3.0.55
 * Contact: apihelp@mailchimp.com
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CustomerJourneysTriggerStepActionRequest;
import com.konfigthis.client.model.CustomerJourneysTriggerStepActiondefaultResponse;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for CustomerJourneysApi
 */
@Disabled
public class CustomerJourneysApiTest {

    private static CustomerJourneysApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new CustomerJourneysApi(apiClient);
    }

    /**
     * Customer Journeys API trigger for a contact
     *
     * A step trigger in a Customer Journey. To use it, create a starting point or step from the Customer Journey builder in the app using the Customer Journeys API condition. We’ll provide a url during the process that includes the {journey_id} and {step_id}. You’ll then be able to use this endpoint to trigger the condition for the posted contact.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void triggerStepActionTest() throws ApiException {
        String emailAddress = null;
        Integer journeyId = null;
        Integer stepId = null;
        Object response = api.triggerStepAction(emailAddress, journeyId, stepId)
                .execute();
        // TODO: test validations
    }

}
